# port
server:
  port: 8100

spring:
  # name
  application:
    name: "currency-conversion"

  # config-server
  config:
    import: "optional:configserver:http://localhost:8888"

# eureka-client-registration
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
