# port
server:
  port: 8100

spring:
  # name
  application:
    name: "currency-conversion"

  # config-server
  config:
    import: "optional:configserver:http://localhost:8888"

  # h2-db
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:testDB"
