# port
server:
  port: 8100

spring:
  # name
  application:
    name: "currency-conversion"

  # zipkin
  zipkin:
    sender:
      type: "web"
    baseUrl: "http://localhost:9411"

  # config-server
  config:
    import: "optional:configserver:http://localhost:8888"

# eureka-client-registration
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"

# zipkin config
management:
  tracing:
    sampling:
      probability: "1.0"

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

